### ISSUE TITLE
I am having this error while installing 

### ISSUE THREAD

**Issue by R34LUS3R** [clarketm/s3recon#1]
$ pip install s3recon 
Collecting s3recon
  Downloading https://files.pythonhosted.org/packages/9c/d4/d762d5b5ece8b91de38a26ef63bc90237cd4c4fd0c48d5f9bcdd89b7fbd1/s3recon-1.1.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-Z4l4PM/s3recon/setup.py", line 11, in <module>
        with open_local(["s3recon", "__init__.py"]) as f:
      File "/tmp/pip-install-Z4l4PM/s3recon/setup.py", line 8, in open_local
        return open(path, mode=mode, encoding=encoding)
    TypeError: 'encoding' is an invalid keyword argument for this function
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-Z4l4PM/s3recon/

**Comment by clarketm** [comment]
@realuser07 - I think the problem is that you are attempting to install using python2  (`pip`) rather than python3 (`pip3`). Unfortunately this repo uses a few non-compatible features and does not work with python2.

**Comment by R34LUS3R** [comment]
Thanks my bad i haven't tried pip3 but i think you should add that to readme document maybe some noob like me get that and didn't ask to any one. :) thanks for building and keep it open source

**Comment by clarketm** [comment]
No problem, I will attempt to make it more explicit in the README that py2 is not supported. Furthermore, if adding support for py2 it non-trivial I can do that as well.

**Comment by R34LUS3R** [comment]
Thanks for the hard work and best of luck for the future!
