### ISSUE TITLE
Install requires

### ISSUE THREAD

**Issue by rishabhdeepsingh** [clarketm/s3recon#5]
add `pymongo` `pyyaml` `requests` to the `install_requires `

**Comment by clarketm** [comment]
Thanks. And sorry, for the delayed reply. I will add these and cut a release.

**Comment by rishabhdeepsingh** [comment]
Thanks a lot. 😄

**Comment by clarketm** [comment]
[v1.3.1](https://github.com/clarketm/s3recon/tree/v1.3.1)
